#!/bin/bash
set -e

source "$(dirname $0)/bootstrap"

export HOME=/root
export PATH=$PATH:/opt/rbenv/bin:$CHARM_DIR/hooks/bin
source $HOME/.bashrc


chef-solo -o "recipe[juju::bootstrap],recipe[rack::install]"
