#!/bin/bash
set -e

export HOME=/root
export PATH=$PATH:/opt/rbenv/bin:$CHARM_DIR/hooks/bin
source $HOME/.bashrc

hook_name=$(basename $0)

if [[ "$hook_name" == *-relation-* ]]; then
  cookbook_name="${hook_name%-relation*}-relation"
  recipe_name=${hook_name#*relation-}
  else
  cookbook_name='rack'
  recipe_name=$hook_name
fi

chef-solo -c /etc/chef/solo.rb -o "recipe[juju::bootstrap],recipe[$cookbook_name::$recipe_name]"
